### ISSUE TITLE
关于数组赋值的问题

### ISSUE THREAD

**Issue by xx1022** [YHN-ice/CFortranTranslator#4]
工具本身对于数组赋值的功能参见demos中的basic.for文件
我们的代码中的需求有一下几种形式
real,dimension(3,4):: a(3,4)=(/1,2,3,4,5,6,7,8,9,10,11,12 /)
real,dimension(3,4):: a(3,4)=(/(/1,2,3/),(/4,5,6/),(/7,8,9/),(/10,11,12/) /) 
real,dimension(3,4)::c = reshape( (/ 1,2,3,4,5,6,7,8,9,10,11,12/), (/ 3, 4 /) )
第一种在工具中可以转换为
        farray<double> a {{1, 1}, {3, 4}};
        a = make_init_list(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12);
但 make_init_list这个函数的定义仍不够完善，转换后的代码无法运行
reshape是Fortran的函数，这三种赋值方式都是以列优先，行列关系的问题工具通过inout的方式转换后形式其实与Fortran相类似了

其中第一种赋值方式其实是省略了data，但之前我们对data的设置没有考虑多维数组
![image](https://user-images.githubusercontent.com/110914563/183665904-38b2d4a6-0cd2-47cd-bd86-e05cf0f22653.png)
我觉得我们可以完善 make_init_list这个函数，参考之前对data的设置

**Comment by YHN-ice** [comment]
test case
```fortran
program main
    implicit none
    real,dimension(3,4):: a(3,4)=(/1,2,3,4,5,6,7,8,9,10,11,12 /)
    real,dimension(3,4):: b(3,4)=(/(/1,2,3/),(/4,5,6/),(/7,8,9/),(/10,11,12/) /)
    real,dimension(3,4)::c = reshape( (/ 1,2,3,4,5,6,7,8,9,10,11,12/), (/ 3, 4 /) )
end program
```

output 
```cpp
/**********************************************************************/
/* File:                                                              */
/* Author:                                                            */
/* This codes is generated by CFortranTranslator                      */
/* CFortranTranslator is published under GPL license                  */
/* refer to https://github.com/CalvinNeo/CFortranTranslator/ for more */
/**********************************************************************/
#include "../for90std/for90std.h" 
#define USE_FORARRAY 
int main()
{
	farray<double> a {{1, 1}, {3, 4}};
	a = make_init_list({1.,2.,3.,4.,5.,6.,7.,8.,9.,10.,11.,12.});
	farray<double> b {{1, 1}, {3, 4}};
	b = forconcat({make_init_list({1.,2.,3.}), make_init_list({4.,5.,6.}), make_init_list({7.,8.,9.}), make_init_list({10.,11.,12.})});
	farray<double> c {{1, 1}, {3, 4}};
	c = forreshape({1.,2.,3.,4.,5.,6.,7.,8.,9.,10.,11.,12.}, {3, 4});
	
	return 0;
}
```

*array a, b and c are with same content and memory layout.*

**Comment by xx1022** [comment]
integer,dimension(3,4),parameter::c(3,4) = reshape( (/ 1,2,3,4,5,6,7,8,9,10,11,12/), (/ 3, 4 /) )
带着parameter的属性之后可以转换为    
const farray<int> c{ {1, 1}, {3, 4} };
    c = forreshape({ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 }, { 3, 4 });
但是无法运行

**Comment by xx1022** [comment]
fortran代码：
program arrayReshape
implicit none
 integer i
 integer,parameter::one=1,zero=0
  integer,dimension(3,12)::a
     do i=1,3
       a(i,1:9) = (/one,zero,zero, zero,one,zero, zero,zero,one/)
     enddo
     write(*,*) a(1,1)
end program arrayReshape

转换结果：
#include "../for90std/for90std.h"
#define USE_FORARRAY
int main()
{
    farray<int> a{ {1, 1}, {3, 12} };
    int i = 0;
    const int one = 1;
    const int zero = 0;
    for (i = 1; i <= 3; i += 1) {
        forslice(a, { {i}, {1, 9} }) = make_init_list({ one, zero, zero, zero, one, zero, zero, zero, one });
    }
    forwritefree(stdout, a(INOUT(1), INOUT(1)));

    return 0;
}

为什么输出后运行数组a都是0呢T T

**Comment by YHN-ice** [comment]
> integer,dimension(3,4),parameter::c(3,4) = reshape( (/ 1,2,3,4,5,6,7,8,9,10,11,12/), (/ 3, 4 /) ) 带着parameter的属性之后可以转换为 const farray c{ {1, 1}, {3, 4} }; c = forreshape({ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 }, { 3, 4 }); 但是无法运行

source file
```cpp
#include "../for90std/for90std.h"
#define USE_FORARRAY
int main()
{
    const farray<int> c {{1, 1}, {3, 4}};
        c = forreshape({1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12}, {3, 4});
    forprintfree(c);
    return 0;
}
```

compile command
```shell
g++  main.cpp -Wall -DPOSIX -g -O3 -fpermissive -fPIC -std=c++17
```

run with `./a.out`,  and output is as the following.
```shell
main.cpp: In function ‘int main()’:
main.cpp:6:64: warning: passing ‘const for90std::farray<int>’ as ‘this’ argument discards qualifiers [-fpermissive]
  c = forreshape({1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12}, {3, 4});
                                                                ^
In file included from ../for90std/formath.h:27:0,
                 from ../for90std/for90std.h:23:
../for90std/farray.h:530:14: note:   in call to ‘for90std::farray<T>& for90std::farray<T>::operator=(for90std::farray<T>&&) [with T = int]’
  farray<T> & move_from(farray<T> && m) {
              ^~~~~~~~
1       2       3       4       5       6       7       8       9     10       11      12
```

seems fine (no error prompt)?
maybe included obsolete head files(e.g., `for1array.h`)?
any detail of not working viable?

**Comment by YHN-ice** [comment]
> fortran代码： program arrayReshape implicit none integer i integer,parameter::one=1,zero=0 integer,dimension(3,12)::a do i=1,3 a(i,1:9) = (/one,zero,zero, zero,one,zero, zero,zero,one/) enddo write(_,_) a(1,1) end program arrayReshape
> 
> 转换结果： #include "../for90std/for90std.h" #define USE_FORARRAY int main() { farray a{ {1, 1}, {3, 12} }; int i = 0; const int one = 1; const int zero = 0; for (i = 1; i <= 3; i += 1) { forslice(a, { {i}, {1, 9} }) = make_init_list({ one, zero, zero, zero, one, zero, zero, zero, one }); } forwritefree(stdout, a(INOUT(1), INOUT(1)));
> 
> ```
> return 0;
> ```
> 
> }
> 
> 为什么输出后运行数组a都是0呢T T

```cpp
/* in file farray.h */
template <typename T, int X>
auto forslice(const farray<T> & farr, const slice_info<fsize_t>(&tp)[X]) {
	// by fortran standard, slice must return by ref
	// `narr` is sliced array of `farr`
	farray<T> narr{}; // dimension will be reset later in reset_array
	slice_info<fsize_t> ntp[X];
	// `narr` can have fewer dimensions than `farr`
	assert(X <= farr.dimension);
	for (auto i = 0; i < X; i++)
	{
		if (tp[i].isall) {
			// [from, to]
			ntp[i] = slice_info<fsize_t>({ farr.LBound(i), farr.UBound(i) });
		}
		else {
			// just copy
			ntp[i] = slice_info<fsize_t>(tp[i]);
		}
	}
	narr.reset_array(ntp, true);
	narr.reset_value();
	// because `narr` can have fewer dimensions than `farr`, `narr.get_delta()` can't be used here
	fsize_t ndelta[X];
	std::transform(ntp, ntp + X, ndelta, [](auto x) {return (x.to + 1 - x.fr) / x.step + ((x.to + 1 - x.fr) % x.step == 0 ? 0 : 1); }); // size
	fa_layer_delta(ndelta, ndelta + X, ndelta);
	_forslice_impl<T, X>(ntp, farr, 0, ndelta, farr.get_delta(), narr.begin(), narr.end(), farr.cbegin(), farr.cend());

	return _RTN(narr);
}
```
This is the definition, the return value is constructed from a new farray, `farray<T> narr{};`, which is independent of the original array `a`, and when assigning a farray to it, `a` in main function is intact.
To resolve, either change the interpretation for slicing array, or change the implementation of `forslice`, e.g., make it return the reference to the original array. Both resolution may need detailed investigation into `farry.h`.

**Comment by xx1022** [comment]
![image](https://user-images.githubusercontent.com/110914563/183932118-4a15d9e6-7a33-4821-8981-28de5205ec14.png)
![image](https://user-images.githubusercontent.com/110914563/183932507-5ac05a8f-939d-4de6-a674-70fafd677a21.png)
分别是有没有const的结果 我检查了是有添加for1array.h头文件的

**Comment by xx1022** [comment]
> > fortran代码： program arrayReshape implicit none integer i integer,parameter::one=1,zero=0 integer,dimension(3,12)::a do i=1,3 a(i,1:9) = (/one,zero,zero, zero,one,zero, zero,zero,one/) enddo write(_,_) a(1,1) end program arrayReshape
> > 转换结果： #include "../for90std/for90std.h" #define USE_FORARRAY int main() { farray a{ {1, 1}, {3, 12} }; int i = 0; const int one = 1; const int zero = 0; for (i = 1; i <= 3; i += 1) { forslice(a, { {i}, {1, 9} }) = make_init_list({ one, zero, zero, zero, one, zero, zero, zero, one }); } forwritefree(stdout, a(INOUT(1), INOUT(1)));
> > ```
> > return 0;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > }
> > 为什么输出后运行数组a都是0呢T T
> 
> ```c++
> /* in file farray.h */
> template <typename T, int X>
> auto forslice(const farray<T> & farr, const slice_info<fsize_t>(&tp)[X]) {
> 	// by fortran standard, slice must return by ref
> 	// `narr` is sliced array of `farr`
> 	farray<T> narr{}; // dimension will be reset later in reset_array
> 	slice_info<fsize_t> ntp[X];
> 	// `narr` can have fewer dimensions than `farr`
> 	assert(X <= farr.dimension);
> 	for (auto i = 0; i < X; i++)
> 	{
> 		if (tp[i].isall) {
> 			// [from, to]
> 			ntp[i] = slice_info<fsize_t>({ farr.LBound(i), farr.UBound(i) });
> 		}
> 		else {
> 			// just copy
> 			ntp[i] = slice_info<fsize_t>(tp[i]);
> 		}
> 	}
> 	narr.reset_array(ntp, true);
> 	narr.reset_value();
> 	// because `narr` can have fewer dimensions than `farr`, `narr.get_delta()` can't be used here
> 	fsize_t ndelta[X];
> 	std::transform(ntp, ntp + X, ndelta, [](auto x) {return (x.to + 1 - x.fr) / x.step + ((x.to + 1 - x.fr) % x.step == 0 ? 0 : 1); }); // size
> 	fa_layer_delta(ndelta, ndelta + X, ndelta);
> 	_forslice_impl<T, X>(ntp, farr, 0, ndelta, farr.get_delta(), narr.begin(), narr.end(), farr.cbegin(), farr.cend());
> 
> 	return _RTN(narr);
> }
> ```
> 
> This is the definition, the return value is constructed from a new farray, , which is independent of the original array , and when assigning a farray to it, in main function is intact. To resolve, either change the interpretation for slicing array, or change the implementation of , e.g., make it return the reference to the original array. Both resolution may need detailed investigation into .`farray<T> narr{};``a``a``forslice``farry.h`

![image](https://user-images.githubusercontent.com/110914563/183942115-0f07c45e-4ddd-4963-ab72-7b2ea9776ad0.png)
![image](https://user-images.githubusercontent.com/110914563/183942253-743f8497-595e-43cc-a771-d743457e5899.png)
我的意思是同样的代码转换前后运行的结果不一样 fortran这段代码表明的意思中a(1,1)应该是赋值为1不是0

**Comment by YHN-ice** [comment]
@xx1022 
- commit 5a5a604acd7620657b078d2d5ab8cadff62bebbe for #4. It is composed of two minor commits.
  1. commit 7e6e1a42f9e86d902a4ad3574586894a4a223580 for const assignment.
  2. commit 179a273573c0a673cd892d8999fa525c540f4997 for slice assignment.

**Comment by xx1022** [comment]
> @xx1022
> 
> * commit [5a5a604](https://github.com/YHN-ice/CFortranTranslator/commit/5a5a604acd7620657b078d2d5ab8cadff62bebbe) for [关于数组赋值的问题 #4](https://github.com/YHN-ice/CFortranTranslator/issues/4). It is composed of two minor commits.
>   
>   1. commit [7e6e1a4](https://github.com/YHN-ice/CFortranTranslator/commit/7e6e1a42f9e86d902a4ad3574586894a4a223580) for const assignment.
>   2. commit [179a273](https://github.com/YHN-ice/CFortranTranslator/commit/179a273573c0a673cd892d8999fa525c540f4997) for slice assignment.

const的那部分 转换和运行没问题 但是如果要输出数组中的值有些问题
<img width="966" alt="1660716391617" src="https://user-images.githubusercontent.com/110914563/185047227-759e4b93-dfe4-46c6-9242-08df653747c1.png">
