### ISSUE TITLE
关于program中的pointer指向module中的target

### ISSUE THREAD

**Issue by xx1022** [YHN-ice/CFortranTranslator#5]
module ma
    type car
        real speed
    end type
    type(car),target::car1
    contains
    subroutine xx(a)
     real a
     write(*,*)a
    end subroutine  
end module  
 
program main
    use ma
    type(car),pointer::car2=>null()
    car1%speed=1.0
    car2=>car1
    call xx(car2%speed)
end program

上述情况（分为两个文件）program段落工具转换不了 原因是type的定义和target在另一个文件中作为头文件

**Comment by bmz-q-q** [comment]
这两段放在一个文件里好像也不行？
引发了异常: 读取访问权限冲突。
_Right_data 是 0x30。

**Comment by bmz-q-q** [comment]
我注释掉三行代码后转换：
module ma
  type car
  real speed
  end type
 type(car),target::car1
  contains
 subroutine xx(a)
 real a
 write(*,*)a
 end subroutine
 end module

program main
use ma
type(car),pointer::car2=>null()
! car1%speed=1.0
! car2=>car1
! call xx(car2%speed)
end program 
结果如下：
#include "../for90std/for90std.h"
#define USE_FORARRAY
void xx(double && a);
#include "ma.h"
#ifndef ma_xx
#define ma_xx
void xx(double && a)
{
        forwritefree(stdout, a);
        return ;
}

#endif
#ifndef ma_car
#define ma_car
struct car
{
        double speed = 0.0;
};
#endif
int main()
{
        car * car2 = NULL;
        return 0;
}#ifndef ma
#define ma
car car1;
#endif

**Comment by xx1022** [comment]
module  ma 
 implicit none
  type car
   real speed
 end type 
 end module
  
program main
 use ma
  type(car) car1
  car1%speed=1.0
end program

这样情况下program段落也会异常，也就是说目前type的声明和指针指向都得与定义在一个段落内（program或module）才能正常识别

**Comment by xx1022** [comment]
> 

一般我们的program和module就放在两个文件里，所以这里module段落可以正常转换，program文件中涉及到type的声明和指向所以会异常

**Comment by xx1022** [comment]
![image](https://user-images.githubusercontent.com/110914563/188264550-5d400beb-b343-4397-98aa-b199c7b47ced.png)
