### ISSUE TITLE
关于赋值后缀问题

### ISSUE THREAD

**Issue by xx1022** [YHN-ice/CFortranTranslator#6]
之前添加的literal_tail语句没有区分五个关键词对应的变量精度
 program main
 real a,b
 integer c,d
 logical e
 data a/1.0_fullR/
 data b/1.0_singR/
 data c/1_fulli/
 data d/1_singi/
 data e/.true._singl/

 write(*,*)a,b,c,d,e
end program

在这里a应该是long double才对 int也有对应的精度（kind=4和kind=8
![image](https://user-images.githubusercontent.com/110914563/185333834-cfa629e8-c6ec-4f6a-8edb-e0d338ce7765.png)

**Comment by YHN-ice** [comment]
他们的精度不是在前面定义时给定了吗？如果后续赋值可以改变一个变量的精度那不是变成动态变量类型吗？

**Comment by xx1022** [comment]
> 他们的精度不是在前面定义时给定了吗？如果后续赋值可以改变一个变量的精度那不是变成动态变量类型吗？

你说得对 因为我一开始理解为开头的定义只是说明浮点数类型 后面的下划线赋予精度 我去查找了代码 不会出现这种情况 所以不用考虑
