### ISSUE TITLE
data

### ISSUE THREAD

**Issue by bmz-q-q** [YHN-ice/CFortranTranslator#8]
character*(256) mat_gob_long(6)
      data mat_gob_long /'Material Potential Energy',                   &
       'Material K.E. (Closed Vol Pres)',                               &
       'Material Mass (Closed Volume)',                                 & 
       'C.G. X-Vel (X-Contact Force)',                                  &
       'C.G. Y-Vel (Y-Contact Force)',                                  &
       'C.G. Z-Vel (Z-Contact Force)'/

从'C.G. X-Vel (X-Contact Force)'开始报错，如果将换行符去掉连为一行可以正常运行。
测试其他带有换行符的data赋值均正常，如果是C.G. X-Vel (X-Contact Force)字符串的问题此问题暂时可忽略，如有类似问题或发现其另有原因则在此问题下讨论。

**Comment by bmz-q-q** [comment]
data stress_comp_long /                                         &   
              'X Stress', 'Y Stress', 'Z Stress',                         &
              'XY Stress', 'YZ Stress','ZX Stress'/
出现同样的问题

**Comment by bmz-q-q** [comment]
```
data sh_mat57_long                                               &
       /'X Stress', 'Y Stress', 'Z Stress','XY Stress', 'YZ Stress',    &
       'ZX Stress', 'Damage Seq.',                                      &
       'Def Grad-11', 'Def Grad-12', 'Def Grad-13',                     &
       'Def Grad-21', 'Def Grad-22', 'Def Grad-23',                     &
       'Def Grad-31', 'Def Grad-32', 'Def Grad-33',                     &
       'COD 0-n'     ,'COD 0-m',                                        &
       'COD 90-n'    ,'COD 90-m',                                       &
       'COD Vel 0-n' ,'COD Vel 0-m',                                    &
       'COD Vel 90-n','COD Vel 90-m',                                   &
       'COD Acc 0-n' ,'COD Acc 0-m',                                    &
       'COD Acc 90-n','COD Acc 90-m',                                   &
       'X0t' ,'X0c' ,'X90t','X90c','Min. Fib. Strain',                  &
       'Plas Strain-11', 'Plas Strain-22',                              &
       'Plas Strain-12', 'Plas Strain-23', 'Plas Strain-13',            &
       'Eqv Plastic Strn.',                                             &
       'Fric. 0 xy','Fric. 90 xy',                                      &
       'Lamina Failure Flag',                                           &
       'Local X-stress','Local Y-stress','Local XY-stress',             &
       'Dir Cosine', 'Dir Sin',                                         &
       'Width 0','Width 90'/
```
![image](https://user-images.githubusercontent.com/98013937/185729258-4c63a975-63a0-4fa4-bae3-c3ee22e83b83.png)

**Comment by xx1022** [comment]
字符串数组data赋初值多个换行问题 ，我试了两个以内是没问题的，三个换行异常，四个会报错……
![image](https://user-images.githubusercontent.com/110914563/185735379-78d13786-bf53-4819-a49d-8d9f7c5803cd.png)
![image](https://user-images.githubusercontent.com/110914563/185735397-4f7c28bc-ff27-4ead-8d75-8acbe9ddb76c.png)
![image](https://user-images.githubusercontent.com/110914563/185735578-7c6bacde-e720-4974-82dd-a4a16c027cb5.png)

**Comment by YHN-ice** [comment]
这里导致错误的是第二列的c/C，其他字母不会出错，或者加空格。原因是识别成了comment，见commit 36cb0ac045fe534ef84199dc86541d71c62a0b84 代码内注释。

**Comment by xx1022** [comment]
![image](https://user-images.githubusercontent.com/110914563/185850678-a760294f-11d6-4ff3-9a89-122e39408b27.png)
我修改之后转换没问题 但是转换后代码无法运行

**Comment by YHN-ice** [comment]
> ![image](https://user-images.githubusercontent.com/110914563/185850678-a760294f-11d6-4ff3-9a89-122e39408b27.png) 我修改之后转换没问题 但是转换后代码无法运行

@xx1022 **Not reproducible**

我的转换结果不一样，或许可以尝试重新生成解决方案/pull最新代码重新compile
```fortran
program main
 character*(256) mat_gob_long(6)
 data mat_gob_long /'a', &
 'b', &
 'c', &
 'd', &
 'e', &
 'f'/
 write(*,*) mat_gob_long
end program
```

转换 `./bin/CFortranTranslator -fF ./demos/2.for > ./demos/2.cpp`
```cpp
/**********************************************************************/
/* File:                                                              */
/* Author:                                                            */
/* This codes is generated by CFortranTranslator                      */
/* CFortranTranslator is published under GPL license                  */
/* refer to https://github.com/CalvinNeo/CFortranTranslator/ for more */
/**********************************************************************/
#include "../for90std/for90std.h" 
#define USE_FORARRAY 
int main()
{
	farray<string> mat_gob_long {{1}, {6}};
	mat_gob_long(INOUT(6)) = SS("f");
	mat_gob_long(INOUT(5)) = SS("e");
	mat_gob_long(INOUT(4)) = SS("d");
	mat_gob_long(INOUT(3)) = SS("c");
	mat_gob_long(INOUT(2)) = SS("b");
	mat_gob_long(INOUT(1)) = SS("a");
	forwritefree(stdout, mat_gob_long);
	
	
	return 0;
}
```

编译 `g++  ./demos/2.cpp -Wall -DPOSIX -g -O3 -fpermissive -fPIC -std=c++17 -o ./demos/a.out`
```shell
In file included from ./demos/2.cpp:8:
In file included from ./demos/../for90std/for90std.h:23:
In file included from ./demos/../for90std/formath.h:27:
./demos/../for90std/farray.h:44:11: warning: unused variable 'ub_i' [-Wunused-variable]
                fsize_t ub_i = LBound[i] + size[i] - 1;
                        ^
In file included from ./demos/2.cpp:8:
In file included from ./demos/../for90std/for90std.h:24:
./demos/../for90std/forstdio.h:303:13: warning: format string is not a string literal (potentially insecure)
      [-Wformat-security]
        fprintf(f, format.strip_front().c_str());
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
./demos/../for90std/forstdio.h:303:13: note: treat the string as an argument to avoid this
        fprintf(f, format.strip_front().c_str());
                   ^
                   "%s", 
./demos/../for90std/forstdio.h:384:13: warning: format string is not a string literal (potentially insecure)
      [-Wformat-security]
        fprintf(f, ss.c_str());
                   ^~~~~~~~~~
./demos/../for90std/forstdio.h:384:13: note: treat the string as an argument to avoid this
        fprintf(f, ss.c_str());
                   ^
                   "%s", 
./demos/../for90std/forstdio.h:392:13: warning: format string is not a string literal (potentially insecure)
      [-Wformat-security]
        fprintf(f, ss.c_str());
                   ^~~~~~~~~~
./demos/../for90std/forstdio.h:392:13: note: treat the string as an argument to avoid this
        fprintf(f, ss.c_str());
                   ^
                   "%s", 
./demos/../for90std/forstdio.h:599:6: warning: unused variable 'res' [-Wunused-variable]
        int res = fscanf(f, "%d", &x);
            ^
5 warnings generated.
```

运行 `./demos/a.out`
=> 
    `a	b	c	d	e	f`

**Comment by xx1022** [comment]
![image](https://user-images.githubusercontent.com/110914563/186648121-b88520c8-93ad-4a5b-886e-57d01057e524.png)
![image](https://user-images.githubusercontent.com/110914563/186648271-30aa65ab-ac54-4e38-b011-b9a0ec5d4521.png)
我试了一下 我这边字符串数组转换后会有      int mat_gob_long(INOUT(1)) = 0;  就不是换行符号的问题了
把int这个内容删掉就可以运行 
这个多余的内容是怎么来的嘞

**Comment by xx1022** [comment]
> > ![image](https://user-images.githubusercontent.com/110914563/185850678-a760294f-11d6-4ff3-9a89-122e39408b27.png) 我修改之后转换没问题 但是转换后代码无法运行
> 
> @xx1022 **Not reproducible**
> 
> 我的转换结果不一样，或许可以尝试重新生成解决方案/pull最新代码重新compile
> 
> ```fortran
> program main
>  character*(256) mat_gob_long(6)
>  data mat_gob_long /'a', &
>  'b', &
>  'c', &
>  'd', &
>  'e', &
>  'f'/
>  write(*,*) mat_gob_long
> end program
> ```
> 
> 转换 `./bin/CFortranTranslator -fF ./demos/2.for > ./demos/2.cpp`
> 
> ```c++
> /**********************************************************************/
> /* File:                                                              */
> /* Author:                                                            */
> /* This codes is generated by CFortranTranslator                      */
> /* CFortranTranslator is published under GPL license                  */
> /* refer to https://github.com/CalvinNeo/CFortranTranslator/ for more */
> /**********************************************************************/
> #include "../for90std/for90std.h" 
> #define USE_FORARRAY 
> int main()
> {
> 	farray<string> mat_gob_long {{1}, {6}};
> 	mat_gob_long(INOUT(6)) = SS("f");
> 	mat_gob_long(INOUT(5)) = SS("e");
> 	mat_gob_long(INOUT(4)) = SS("d");
> 	mat_gob_long(INOUT(3)) = SS("c");
> 	mat_gob_long(INOUT(2)) = SS("b");
> 	mat_gob_long(INOUT(1)) = SS("a");
> 	forwritefree(stdout, mat_gob_long);
> 	
> 	
> 	return 0;
> }
> ```
> 
> 编译 `g++ ./demos/2.cpp -Wall -DPOSIX -g -O3 -fpermissive -fPIC -std=c++17 -o ./demos/a.out`
> 
> ```shell
> In file included from ./demos/2.cpp:8:
> In file included from ./demos/../for90std/for90std.h:23:
> In file included from ./demos/../for90std/formath.h:27:
> ./demos/../for90std/farray.h:44:11: warning: unused variable 'ub_i' [-Wunused-variable]
>                 fsize_t ub_i = LBound[i] + size[i] - 1;
>                         ^
> In file included from ./demos/2.cpp:8:
> In file included from ./demos/../for90std/for90std.h:24:
> ./demos/../for90std/forstdio.h:303:13: warning: format string is not a string literal (potentially insecure)
>       [-Wformat-security]
>         fprintf(f, format.strip_front().c_str());
>                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ./demos/../for90std/forstdio.h:303:13: note: treat the string as an argument to avoid this
>         fprintf(f, format.strip_front().c_str());
>                    ^
>                    "%s", 
> ./demos/../for90std/forstdio.h:384:13: warning: format string is not a string literal (potentially insecure)
>       [-Wformat-security]
>         fprintf(f, ss.c_str());
>                    ^~~~~~~~~~
> ./demos/../for90std/forstdio.h:384:13: note: treat the string as an argument to avoid this
>         fprintf(f, ss.c_str());
>                    ^
>                    "%s", 
> ./demos/../for90std/forstdio.h:392:13: warning: format string is not a string literal (potentially insecure)
>       [-Wformat-security]
>         fprintf(f, ss.c_str());
>                    ^~~~~~~~~~
> ./demos/../for90std/forstdio.h:392:13: note: treat the string as an argument to avoid this
>         fprintf(f, ss.c_str());
>                    ^
>                    "%s", 
> ./demos/../for90std/forstdio.h:599:6: warning: unused variable 'res' [-Wunused-variable]
>         int res = fscanf(f, "%d", &x);
>             ^
> 5 warnings generated.
> ```
> 
> 运行 `./demos/a.out` => `a b c d e f`

没问题了是之前y文件data那个地方改的不完整 我同步了代码之后就没问题
